<?php
/**
 * AddressTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  GarageWeek
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/*
* Garage Week 2021. All rights reserved.
* Your custom license text goes here.
*/

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GarageWeek\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class
 * @description Address
 * @package     GarageWeek
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
